### ISSUE TITLE
报错，找不到gs文件

### ISSUE THREAD

**Issue by xl-1221** [ucas-vg/GroupSampling#1]

**Comment by henrysun1996** [comment]
请问这个代码是不是有问题啊？我还没跑，看到你这个问题怕白忙活了

**Comment by wavinflaghxm** [comment]
Have you done ```python setup.py develop``` in https://github.com/ucas-vg/GroupSampling#installation?

**Comment by henrysun1996** [comment]
> Have you done `python setup.py develop` in https://github.com/ucas-vg/GroupSampling#install
 i don't try   because i am afraid that it's can't train

**Comment by wavinflaghxm** [comment]
> > Have you done `python setup.py develop` in https://github.com/ucas-vg/GroupSampling#install
> > i don't try   because i am afraid that it's can't train

Cannot find ‘gs’ probably because he hasn't done  ```python setup.py develop```.

**Comment by henrysun1996** [comment]
> > > Have you done `python setup.py develop` in https://github.com/ucas-vg/GroupSampling#install
> > > i don't try   because i am afraid that it's can't train
> 
> Cannot find ‘gs’ probably because he hasn't done `python setup.py develop`.

it means code can be trained?

**Comment by wavinflaghxm** [comment]
> > > > Have you done `python setup.py develop` in https://github.com/ucas-vg/GroupSampling#install
> > > > i don't try   because i am afraid that it's can't train
> > 
> > 
> > Cannot find ‘gs’ probably because he hasn't done `python setup.py develop`.
> 
> it means code can be trained?

Yes. If you have any problem, you can continue to contact me and I will fix it.

**Comment by henrysun1996** [comment]
> > > > > Have you done `python setup.py develop` in https://github.com/ucas-vg/GroupSampling#install
> > > > > i don't try   because i am afraid that it's can't train
> > > 
> > > 
> > > Cannot find ‘gs’ probably because he hasn't done `python setup.py develop`.
> > 
> > 
> > it means code can be trained?
> 
> Yes. If you have any problem, you can continue to contact me and I will fix it.

ok thanks

**Comment by Aicha-kha** [comment]
hello 
hope you are doing well .
please i want to ask you about  this command "python setup.py develop" it doesn't work for me 
after runing it gives me this error : 
(Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from gs import datasets
ImportError: cannot import name 'datasets' from 'gs' (/home/myuser/.local/lib/python3.8/site-packages/gs/__init__.py) )
please can you tell me what can i do to fix it 
thank you !

**Comment by wavinflaghxm** [comment]
> 

Cannot find ‘gs’ probably because you didn't setup the code: `python setup.py develop`.

**Comment by real-wind** [comment]
#绝对路径导入
import sys
sys.path.append('/home/zsc/ReID/GroupSampling-master')

**Comment by real-wind** [comment]
上面的路径根据自己环境改成GroupSampling-master所在的路径
