### ISSUE TITLE
list_train.txt

### ISSUE THREAD

**Issue by vegetablebird5** [ucas-vg/GroupSampling#3]
你好，请问哪里可以找到list_train.txt等文件，训练msmt17数据集时，出现这个错误。
![image](https://user-images.githubusercontent.com/85222184/131211958-ba17a1bb-a212-42ab-ada6-d6bf7224546b.png)

**Comment by wavinflaghxm** [comment]
The list files for MSMT17_V2 can be found at https://drive.google.com/drive/folders/1bNfB5PciW6Bw5TLWWi1FZ__Q9-lemnDl?usp=sharing. But it is recommended that you send an email to the owner of the dataset for a request.

**Comment by vegetablebird5** [comment]
okay，Thanks a lot ，I got it. 请问MSMT17和MSMT_V2数据集有区别吗？

**Comment by vegetablebird5** [comment]
我使用MSMT17数据集进行训练时，出现了以下错误。
![image](https://user-images.githubusercontent.com/85222184/131212816-78fb50e1-e92b-431f-b402-5a303ee9b991.png)

**Comment by wavinflaghxm** [comment]
> okay，Thanks a lot ，I got it. 请问MSMT17和MSMT_V2数据集有区别吗？

Faces are masked in V2, but not in V1.

**Comment by wavinflaghxm** [comment]
> 我使用MSMT17数据集进行训练时，出现了以下错误。
> ![image](https://user-images.githubusercontent.com/85222184/131212816-78fb50e1-e92b-431f-b402-5a303ee9b991.png)

I think this is because the dataset file composition is different, so I suggest you ask the author.
