### ISSUE TITLE
About MSMT17 dataset

### ISSUE THREAD

**Issue by rerester** [ucas-vg/GroupSampling#4]
The dataset MSMT17 homepage [http://www.pkuvmc.com/publications/msmt17.html](http://www.pkuvmc.com/publications/msmt17.html ) appears to be invalid.

Is there a link of google drive for downloading MSMT17 dataset?

**Comment by wavinflaghxm** [comment]
You need to send an email to the owner (slzhang.jdl@pku.edu.cn) for a request.

**Comment by rerester** [comment]
> You need to send an email to the owner ([slzhang.jdl@pku.edu.cn](mailto:slzhang.jdl@pku.edu.cn)) for a request.

ok, thanks
