### ISSUE TITLE
The results of the experiment cannot be reproduced

### ISSUE THREAD

**Issue by HardWayShip** [ucas-vg/GroupSampling#7]
Hi！ 
After reproducing your code, I found that I couldn't get the same experimental results as your article.  :(

So I want to ask for your help and look forward to your reply.  :)

Thanks and best wishes.

It's the para and data list for dukemtmc
![image](https://user-images.githubusercontent.com/92527626/138805943-2dfc4b87-cb82-4816-be6b-58f22637c82e.png)

and it's the final result
![image](https://user-images.githubusercontent.com/92527626/138806004-6d9a6e66-38d3-4d95-a89d-4d4d028c1743.png)

By the way, I also use one GPU **NVIDIA Tesla P100**  to run this project.

**Comment by wavinflaghxm** [comment]
> Hi！ After reproducing your code, I found that I couldn't get the same experimental results as your article. :(
> 
> So I want to ask for your help and look forward to your reply. :)
> 
> Thanks and best wishes.
> 
> It's the para and data list for dukemtmc ![image](https://user-images.githubusercontent.com/92527626/138805943-2dfc4b87-cb82-4816-be6b-58f22637c82e.png)
> 
> and it's the final result ![image](https://user-images.githubusercontent.com/92527626/138806004-6d9a6e66-38d3-4d95-a89d-4d4d028c1743.png)
> 
> By the way, I also use one GPU **NVIDIA Tesla P100** to run this project.

Maybe you can try to increase group_n.

**Comment by wavinflaghxm** [comment]
You can send the log.txt to my e-mail: hanxumeng19@mails.ucas.ac.cn.

**Comment by HardWayShip** [comment]
> You can send the log.txt to my e-mail: [hanxumeng19@mails.ucas.ac.cn](mailto:hanxumeng19@mails.ucas.ac.cn).

Thanks! I have sent the log.txt just now to you ~  :)
Looking forward to your reply~ :）
